// 8Router — CLI Tool Integration Registry (Phase 2G)

import type { ToolIntegration } from './types.js';

const tools: ToolIntegration[] = [
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'ide',
    status: 'supported',
    description: 'AI-first code editor with custom OpenAI-compatible endpoint support',
    docsUrl: 'https://docs.cursor.com',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: true,
    supportsHeaders: false,
    configFormat: 'ui_steps',
    templates: [
      {
        id: 'cursor-settings',
        label: 'Cursor Settings',
        format: 'ui_steps',
        description: 'Configure 8Router as a custom OpenAI provider in Cursor',
        content: [
          '1. Open Cursor Settings (Ctrl+, or Cmd+,)',
          '2. Navigate to Models > OpenAI API Key',
          '3. Click "Add Model" or edit existing provider',
          '4. Set Base URL: {{BASE_URL}}',
          '5. Set API Key: Enter your 8Router access key',
          '6. Set Model: {{MODEL}}',
          '7. Save and restart Cursor if needed',
        ].join('\n'),
      },
    ],
    notes: [
      'Cursor uses its own API format for some features',
      'Tool/function calling support depends on the underlying model',
    ],
  },
  {
    id: 'cline',
    name: 'Cline',
    category: 'ide',
    status: 'supported',
    description: 'AI coding assistant for VS Code with OpenAI-compatible support',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: true,
    supportsHeaders: false,
    configFormat: 'ui_steps',
    templates: [
      {
        id: 'cline-setup',
        label: 'Cline Configuration',
        format: 'ui_steps',
        description: 'Configure Cline to use 8Router',
        content: [
          '1. Open VS Code with Cline extension installed',
          '2. Click the Cline icon in the sidebar',
          '3. Open Cline Settings (gear icon)',
          '4. Set API Provider: OpenAI Compatible',
          '5. Set Base URL: {{BASE_URL}}',
          '6. Set API Key: Enter your 8Router access key',
          '7. Set Model ID: {{MODEL}}',
          '8. Save settings',
        ].join('\n'),
      },
    ],
    notes: [
      'Recommended model: 8router/coding for best coding performance',
    ],
  },
  {
    id: 'continue',
    name: 'Continue',
    category: 'ide',
    status: 'supported',
    description: 'Open-source AI code assistant for VS Code and JetBrains',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: true,
    supportsHeaders: false,
    configFormat: 'json',
    templates: [
      {
        id: 'continue-config',
        label: 'Continue Config (JSON)',
        format: 'json',
        language: 'json',
        description: 'Continue configuration file',
        content: JSON.stringify({
          models: [
            {
              title: '8Router {{MODEL}}',
              provider: 'openai',
              model: '{{MODEL}}',
              apiBase: '{{BASE_URL}}',
              apiKey: '{{API_KEY}}',
            },
          ],
        }, null, 2),
      },
    ],
    notes: [
      'Place config in .continue/config.json or ~/.continue/config.json',
      'Restart Continue after changing config',
    ],
  },
  {
    id: 'roo-code',
    name: 'Roo Code',
    category: 'ide',
    status: 'supported',
    description: 'AI coding assistant for VS Code with OpenAI-compatible support',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: true,
    supportsHeaders: false,
    configFormat: 'ui_steps',
    templates: [
      {
        id: 'roo-code-setup',
        label: 'Roo Code Settings',
        format: 'ui_steps',
        description: 'Configure Roo Code to use 8Router',
        content: [
          '1. Open VS Code with Roo Code extension',
          '2. Open Roo Code settings',
          '3. Select provider: OpenAI Compatible',
          '4. Set Base URL: {{BASE_URL}}',
          '5. Set API Key: Enter your 8Router access key',
          '6. Set Model: {{MODEL}}',
          '7. Apply settings',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'openwebui',
    name: 'Open WebUI',
    category: 'webui',
    status: 'supported',
    description: 'Self-hosted web interface for LLMs with OpenAI API support',
    docsUrl: 'https://docs.openwebui.com',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: false,
    supportsHeaders: true,
    configFormat: 'ui_steps',
    templates: [
      {
        id: 'openwebui-setup',
        label: 'Open WebUI Settings',
        format: 'ui_steps',
        description: 'Configure Open WebUI to connect to 8Router',
        content: [
          '1. Open Open WebUI admin panel',
          '2. Go to Settings > Connections > OpenAI',
          '3. Set API Base URL: {{BASE_URL}}',
          '4. Set API Key: Enter your 8Router access key',
          '5. Click "Save"',
          '6. Models should refresh — select {{MODEL}}',
          '',
          'NOTE: If running in Docker, localhost will not reach the host.',
          'Use host.docker.internal:8081 or your server LAN IP instead.',
        ].join('\n'),
      },
    ],
    notes: [
      'When running in Docker, localhost refers to the container itself',
      'Disable proxy buffering for SSE streaming support',
    ],
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    category: 'cli',
    status: 'experimental',
    description: 'Anthropic CLI coding tool — OpenAI-compatible support is partial',
    supportsCustomBaseUrl: true,
    supportsCustomModel: false,
    supportsStreaming: true,
    supportsToolCalling: true,
    supportsHeaders: true,
    configFormat: 'env',
    templates: [
      {
        id: 'claude-code-env',
        label: 'Environment Variables',
        format: 'env',
        description: 'Set environment variables for OpenAI-compatible mode (experimental)',
        content: 'OPENAI_BASE_URL={{BASE_URL}}\nOPENAI_API_KEY={{API_KEY}}\nOPENAI_MODEL={{MODEL}}',
      },
    ],
    notes: [
      'Experimental: Claude Code may not fully support all OpenAI-compatible features',
      'Model selection may be limited',
      'Function calling behavior may differ from native Claude',
    ],
  },
  {
    id: 'codex',
    name: 'Codex CLI / OpenAI CLI',
    category: 'cli',
    status: 'experimental',
    description: 'OpenAI-compatible CLI clients using the standard API format',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: true,
    supportsHeaders: true,
    configFormat: 'env',
    templates: [
      {
        id: 'codex-env',
        label: 'Environment Variables',
        format: 'env',
        description: 'Set environment variables for OpenAI-compatible CLI',
        content: 'OPENAI_BASE_URL={{BASE_URL}}\nOPENAI_API_KEY={{API_KEY}}\nOPENAI_MODEL={{MODEL}}',
      },
    ],
    notes: [
      'Model can also be passed via --model flag in most tools',
    ],
  },
  {
    id: 'openai-sdk',
    name: 'OpenAI SDK',
    category: 'sdk',
    status: 'supported',
    description: 'Official OpenAI Python and Node.js SDK with custom base URL',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: true,
    supportsHeaders: true,
    configFormat: 'code',
    templates: [
      {
        id: 'openai-node',
        label: 'Node.js (openai package)',
        format: 'code',
        language: 'javascript',
        description: 'OpenAI Node.js SDK with custom base URL',
        content: [
          "import OpenAI from 'openai';",
          '',
          'const client = new OpenAI({',
          "  baseURL: '{{BASE_URL}}',",
          "  apiKey: '{{API_KEY}}',",
          '});',
          '',
          'const response = await client.chat.completions.create({',
          "  model: '{{MODEL}}',",
          "  messages: [{ role: 'user', content: 'Hello from 8Router' }],",
          '});',
          '',
          "console.log(response.choices[0].message.content);",
        ].join('\n'),
      },
      {
        id: 'openai-python',
        label: 'Python (openai package)',
        format: 'code',
        language: 'python',
        description: 'OpenAI Python SDK with custom base URL',
        content: [
          'from openai import OpenAI',
          '',
          'client = OpenAI(',
          "    base_url='{{BASE_URL}}',",
          "    api_key='{{API_KEY}}',",
          ')',
          '',
          'response = client.chat.completions.create(',
          "    model='{{MODEL}}',",
          "    messages=[{'role': 'user', 'content': 'Hello from 8Router'}],",
          ')',
          '',
          'print(response.choices[0].message.content)',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'curl',
    name: 'cURL',
    category: 'generic',
    status: 'supported',
    description: 'Command-line HTTP client for testing and scripting',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: false,
    supportsHeaders: true,
    configFormat: 'shell',
    templates: [
      {
        id: 'curl-chat',
        label: 'Chat Completion',
        format: 'shell',
        language: 'bash',
        description: 'Test 8Router with cURL',
        content: [
          "curl {{BASE_URL}}/chat/completions \\",
          "  -H 'Authorization: Bearer {{API_KEY}}' \\",
          "  -H 'Content-Type: application/json' \\",
          "  -d '{",
          '    "model": "{{MODEL}}",',
          '    "messages": [',
          '      {"role": "user", "content": "Hello from 8Router"}',
          '    ]',
          "  }'",
        ].join('\n'),
      },
      {
        id: 'curl-models',
        label: 'List Models',
        format: 'shell',
        language: 'bash',
        description: 'List available models via 8Router',
        content: [
          "curl {{BASE_URL}}/models \\",
          "  -H 'Authorization: Bearer {{API_KEY}}'",
        ].join('\n'),
      },
    ],
  },
  {
    id: 'env-file',
    name: 'Environment File',
    category: 'generic',
    status: 'supported',
    description: 'Standard .env file format for application configuration',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: false,
    supportsToolCalling: false,
    supportsHeaders: false,
    configFormat: 'env',
    templates: [
      {
        id: 'env-example',
        label: '.env.example',
        format: 'env',
        description: 'Environment variables for 8Router integration',
        content: [
          'EIGHTROUTER_BASE_URL={{BASE_URL}}',
          'EIGHTROUTER_API_KEY={{API_KEY}}',
          'EIGHTROUTER_MODEL={{MODEL}}',
        ].join('\n'),
      },
    ],
    notes: [
      'Add .env to your .gitignore — never commit API keys',
      'Use placeholder values in shared/example files',
    ],
  },
  {
    id: 'aider',
    name: 'Aider',
    category: 'cli',
    status: 'experimental',
    description: 'AI pair programming in your terminal',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: false,
    supportsHeaders: true,
    configFormat: 'shell',
    templates: [
      {
        id: 'aider-command',
        label: 'Aider Command',
        format: 'shell',
        language: 'bash',
        description: 'Launch Aider with 8Router',
        content: [
          "OPENAI_API_BASE={{BASE_URL}} \\",
          "OPENAI_API_KEY={{API_KEY}} \\",
          "aider --model openai/{{MODEL}}",
        ].join('\n'),
      },
    ],
    notes: [
      'Experimental: verify Aider current OpenAI-compatible support',
    ],
  },
  {
    id: 'librechat',
    name: 'LibreChat',
    category: 'webui',
    status: 'coming_soon',
    description: 'Enhanced ChatGPT clone with multi-model support',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: false,
    supportsHeaders: true,
    configFormat: 'yaml',
    templates: [],
    notes: ['Configuration guide coming soon'],
  },
  {
    id: 'lobechat',
    name: 'LobeChat',
    category: 'webui',
    status: 'coming_soon',
    description: 'Modern open-source ChatGPT/LLM UI framework',
    supportsCustomBaseUrl: true,
    supportsCustomModel: true,
    supportsStreaming: true,
    supportsToolCalling: true,
    supportsHeaders: true,
    configFormat: 'ui_steps',
    templates: [],
    notes: ['Configuration guide coming soon'],
  },
  {
    id: 'zed',
    name: 'Zed',
    category: 'ide',
    status: 'coming_soon',
    description: 'High-performance code editor with AI assistance',
    supportsCustomBaseUrl: false,
    supportsCustomModel: false,
    supportsStreaming: true,
    supportsToolCalling: false,
    supportsHeaders: false,
    configFormat: 'json',
    templates: [],
    notes: ['Custom endpoint support not yet verified in current Zed release'],
  },
];

/** Get all registered tools (safe metadata only) */
export function getToolRegistry(): ToolIntegration[] {
  return tools;
}

/** Get a single tool by ID */
export function getToolById(id: string): ToolIntegration | undefined {
  return tools.find(t => t.id === id);
}

/** Get tools by category */
export function getToolsByCategory(category: string): ToolIntegration[] {
  return tools.filter(t => t.category === category);
}

/** Get tool IDs (for allowlist validation) */
export function getAllToolIds(): string[] {
  return tools.map(t => t.id);
}
