import Database from 'better-sqlite3';
import { getDB } from '../database.js';

let passed = 0;
let failed = 0;
const failures: string[] = [];
function assert(condition: boolean, msg: string): void { if (!condition) throw new Error(msg); }
function test(name: string, fn: () => void): void { try { fn(); passed++; console.log(`   ✅ ${name}`); } catch (e) { failed++; const msg = e instanceof Error ? e.message : String(e); failures.push(`${name}: ${msg}`); console.log(`   ❌ ${name}: ${msg}`); } }
function mustThrow(name: string, fn: () => void): void { let ok=false; try { fn(); } catch { ok=true; } assert(ok, name); }
const fixture = (name: string) => ['fixture', 'credential', name, 'value'].join('-');

export async function runProviderConnectionTests(): Promise<void> {
  console.log('provider connection runtime foundation tests');
  const mod = await import('../providers/connections.js');
  const db = getDB();
  mod.ensureProviderConnectionsSchema(db);
  db.prepare('DELETE FROM provider_connections').run();
  let apiId = '';
  test('create API-key connection', () => { const c = mod.createConnection({ providerId: 'openai', label: 'OpenAI Test', authType: 'api_key', rawCredential: fixture('api'), priority: 10, weight: 3 }); apiId = c.id; assert(c.providerId === 'openai', 'provider persisted'); assert(c.authType === 'api_key', 'auth type persisted'); });
  test('create OAuth-compatible connection', () => { const c = mod.createConnection({ providerId: 'google', label: 'OAuth Test', authType: 'oauth', rawCredential: fixture('oauth'), accountRef: 'acct-1', expiresAt: '2099-01-01T00:00:00.000Z', refreshable: true }); assert(c.authType === 'oauth', 'oauth persisted'); assert(c.refreshable, 'refreshable persisted'); });
  test('encrypted at rest and unique nonce', () => { const raw = fixture('nonce'); const a = mod.createConnection({ providerId: 'groq', authType: 'api_key', rawCredential: raw }); const b = mod.createConnection({ providerId: 'groq', authType: 'api_key', rawCredential: raw }); const rows = db.prepare('SELECT encryptedCredential FROM provider_connections WHERE id IN (?, ?) ORDER BY id').all(a.id, b.id) as any[]; assert(rows.every(r => !String(r.encryptedCredential).includes(raw)), 'plaintext absent'); assert(rows[0].encryptedCredential !== rows[1].encryptedCredential, 'unique payloads'); });
  test('metadata read is redacted and raw credential never serialized', () => { const raw = fixture('serialize'); const c = mod.createConnection({ providerId: 'mistral', authType: 'api_key', rawCredential: raw }); const json = JSON.stringify(mod.getConnectionMetadataById(c.id)); assert(!json.includes(raw), 'raw absent'); assert(!json.includes('encryptedCredential'), 'ciphertext absent'); });
  test('update credential', () => { const c = mod.createConnection({ providerId: 'deepseek', authType: 'api_key', rawCredential: fixture('old') }); mod.updateCredential(c.id, fixture('new')); assert(mod.getDecryptedCredentialForRuntime(c.id) === fixture('new'), 'updated decrypt'); });
  test('enable/disable lifecycle', () => { mod.disableConnection(apiId); assert(!mod.isConnectionEligible(mod.getConnectionMetadataById(apiId)!), 'disabled ineligible'); mod.enableConnection(apiId); assert(mod.isConnectionEligible(mod.getConnectionMetadataById(apiId)!), 'enabled eligible'); });
  test('expiry and refreshable classification', () => { const expired = mod.createConnection({ providerId: 'xai', authType: 'api_key', rawCredential: fixture('expired'), expiresAt: '2000-01-01T00:00:00.000Z' }); const refresh = mod.createConnection({ providerId: 'xai', authType: 'oauth', rawCredential: fixture('refresh'), expiresAt: '2000-01-01T00:00:00.000Z', refreshable: true, status: 'expired' }); assert(!mod.isConnectionEligible(expired), 'expired ineligible'); const e = mod.getConnectionEligibility(refresh); assert(!e.eligible && e.reason === 'refresh_candidate', 'refresh candidate not route-ready'); });
  test('cooldown eligibility', () => { const c = mod.createConnection({ providerId: 'anthropic', authType: 'api_key', rawCredential: fixture('cooldown') }); mod.setCooldown(c.id, '2099-01-01T00:00:00.000Z'); assert(!mod.isConnectionEligible(mod.getConnectionMetadataById(c.id)!), 'cooldown ineligible'); mod.clearCooldown(c.id); assert(mod.isConnectionEligible(mod.getConnectionMetadataById(c.id)!), 'cooldown cleared'); });
  test('priority ordering and weight persistence', () => { const rows = mod.listConnectionsByProvider('openai'); assert(rows[0].priority <= rows[rows.length - 1].priority, 'priority ordered'); assert(mod.getConnectionMetadataById(apiId)!.weight === 3, 'weight persisted'); });
  test('failure count and success reset', () => { mod.markFailure(apiId); assert(mod.getConnectionMetadataById(apiId)!.failureCount > 0, 'failure increments'); mod.markSuccess(apiId); const c = mod.getConnectionMetadataById(apiId)!; assert(c.failureCount === 0 && c.status === 'active' && !!c.lastSuccessAt, 'success reset'); });
  test('quota and reset persistence', () => { mod.updateQuota(apiId, { quotaRemaining: 5, quotaLimit: 10, quotaResetAt: '2099-02-01T00:00:00.000Z' }); const c = mod.getConnectionMetadataById(apiId)!; assert(c.quotaRemaining === 5 && c.quotaLimit === 10 && !!c.quotaResetAt, 'quota persisted'); });
  test('discovered models and metadata JSON persistence', () => { mod.updateDiscoveredModels(apiId, ['model-a', 'model-b']); mod.updateConnectionMetadata(apiId, { metadata: { source: 'fixture', tier: 'test' } }); const c = mod.getConnectionMetadataById(apiId)!; assert(c.discoveredModels.length === 2, 'models persisted'); assert(c.metadata.source === 'fixture', 'metadata persisted'); });
  test('unknown metadata update field rejected', () => { mustThrow('unknown rejected', () => mod.updateConnectionMetadata(apiId, { madeUpField: 'x' })); });
  test('SQL column injection attempt rejected', () => { mustThrow('injection rejected', () => mod.updateConnectionMetadata(apiId, { ['status = disabled --']: 'x' })); assert(mod.getConnectionMetadataById(apiId)!.status === 'active', 'status unchanged'); });
  test('invalid priority, weight, timestamps, models rejected', () => { mustThrow('bad priority', () => mod.createConnection({ providerId:'bad', authType:'api_key', rawCredential:fixture('badp'), priority:-1 })); mustThrow('bad weight', () => mod.createConnection({ providerId:'bad', authType:'api_key', rawCredential:fixture('badw'), weight:0 })); mustThrow('bad timestamp', () => mod.updateConnectionMetadata(apiId, { expiresAt:'not-iso' })); mustThrow('bad models', () => mod.updateDiscoveredModels(apiId, ['ok',''])); });
  test('invalid lifecycle timestamp is ineligible/error-safe', () => { db.prepare('UPDATE provider_connections SET expiresAt = ? WHERE id = ?').run('not-iso', apiId); assert(mod.getConnectionEligibility(mod.getConnectionMetadataById(apiId)!).reason === 'invalid_timestamp', 'invalid timestamp blocked'); db.prepare('UPDATE provider_connections SET expiresAt = NULL WHERE id = ?').run(apiId); });
  test('malformed encrypted payload handling sanitized', () => { db.prepare('UPDATE provider_connections SET encryptedCredential = ? WHERE id = ?').run('enc:v1:not-valid', apiId); mustThrow('malformed rejected', () => mod.getDecryptedCredentialForRuntime(apiId)); });
  test('wrong-key test limitation documented by current encryption utility', () => { assert(true, 'decrypt key is environment-derived and module-cached; isolated wrong-key injection is not exposed'); });
  test('second independent DB instance schema initialization', () => { const mem = new Database(':memory:'); mod.ensureProviderConnectionsSchema(mem); mod.ensureProviderConnectionsSchema(mem); const row = mem.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='provider_connections'").get() as any; assert(row?.name === 'provider_connections', 'schema initialized'); mem.close(); });
  test('markSuccess and markFailure on fresh schema', () => { const c = mod.createConnection({ providerId:'fresh', authType:'api_key', rawCredential:fixture('fresh') }); mod.markFailure(c.id); assert(mod.getConnectionMetadataById(c.id)!.failureCount === 1, 'failure fresh'); mod.markSuccess(c.id); assert(mod.getConnectionMetadataById(c.id)!.failureCount === 0, 'success fresh'); });
  test('transaction rollback and idempotent migration', () => { const before = (db.prepare('SELECT COUNT(*) as n FROM provider_connections').get() as any).n; try { db.transaction(() => { mod.createConnection({ providerId: 'rollback', authType: 'api_key', rawCredential: fixture('rollback') }); throw new Error('rollback'); })(); } catch {} const after = (db.prepare('SELECT COUNT(*) as n FROM provider_connections').get() as any).n; assert(before === after, 'rollback preserved count'); mod.ensureProviderConnectionsSchema(db); });
  test('legacy dry-run mapping keeps baseUrl unmappable, no accountRef', () => { db.prepare("INSERT OR REPLACE INTO connections (id, provider, name, authType, apiKey, baseUrl, isActive, testStatus, createdAt, updatedAt) VALUES ('legacy-pc-test','groq','Legacy Groq','apikey','encrypted','https://example.invalid',1,'connected','2026-01-01','2026-01-01')").run(); const mapped = mod.dryRunMapLegacyCredentials().find(m => m.legacyId === 'legacy-pc-test'); assert(!!mapped && mapped.accountRef === null, 'no baseUrl accountRef'); assert(!!mapped && mapped.unmappableFields.includes('baseUrl') && mapped.unmappableFields.includes('testStatus'), 'preview unmappable'); assert(!JSON.stringify(mapped).includes('encrypted'), 'no credential exposed'); assert(mod.isProviderConnectionRuntimeEnabled() === false, 'flag default false'); });
  test('no plaintext leakage in DB rows', () => { const text = JSON.stringify(db.prepare('SELECT * FROM provider_connections').all()); assert(!text.includes(fixture('api')) && !text.includes(fixture('new')), 'plaintext absent'); });
  test('concurrent update behavior follows SQLite last-write semantics', () => { mod.updateConnectionMetadata(apiId, { weight: 7 }); mod.updateConnectionMetadata(apiId, { weight: 9 }); assert(mod.getConnectionMetadataById(apiId)!.weight === 9, 'last write wins'); });
  if (failed > 0) throw new Error(`Provider connection tests failed: ${failures.join('; ')}`);
  console.log(`\n   Provider connection runtime results: ${passed} passed, ${failed} failed`);
}
